#pragma once


enum GraphicsEventDef
{
	EVENT_GRAPHICS_SETDISPLAYMODE,		//设置显示模式
	EVENT_GRAPHICS_BEGINRENDERING,		//渲染开始
	EVENT_GRAPHICS_ENDRENDERING,		//渲染结束
	EVENT_GRAPHICS_BEGINVIEWUPDATE,		//view更新开始
	EVENT_GRAPHICS_ENDVIEWUPDATE,		//view更新结束
	EVENT_GRAPHICS_DEVICELOST,			//设备丢失
	EVENT_GRAPHICS_DEVICERESET,			//设备重置
	EVENT_GRAPHICS_WINDOWCHANGED,			//窗口改变
	EVENT_GRAPHICS_RENDERSURFACEUPDATE,   //渲染表面更新
	EVENT_GRAPHICS_MAXCOUNT
};