#pragma once


enum GraphicsEventDef
{
	EVENT_GRAPHICS_SETDISPLAYMODE,
	EVENT_GRAPHICS_BEGINRENDERING,
	EVENT_GRAPHICS_ENDRENDERING,
	EVENT_GRAPHICS_BEGINVIEWUPDATE,
	EVENT_GRAPHICS_ENDVIEWUPDATE,
	EVENT_GRAPHICS_DEVICELOST,
	EVENT_GRAPHICS_DEVICERESET,
	EVENT_GRAPHICS_WINDOWCHANGED,
	EVENT_GRAPHICS_MAXCOUNT
};