#pragma once


//用掩码来测试鼠标按键状态
#define MOUSE_BUTTON(X)       (1 << ((X)-1))
#define MOUSE_BUTTON_LEFT     1
#define MOUSE_BUTTON_MIDDLE   2
#define MOUSE_BUTTON_RIGHT    3
#define MOUSE_BUTTON_X1       4
#define MOUSE_BUTTON_X2       5
#define MOUSE_BUTTON_LMASK    MOUSE_BUTTON(MOUSE_BUTTON_LEFT)
#define MOUSE_BUTTON_MMASK    MOUSE_BUTTON(MOUSE_BUTTON_MIDDLE)
#define MOUSE_BUTTON_RMASK    MOUSE_BUTTON(MOUSE_BUTTON_RIGHT)
#define MOUSE_BUTTON_X1MASK   MOUSE_BUTTON(MOUSE_BUTTON_X1)
#define MOUSE_BUTTON_X2MASK   MOUSE_BUTTON(MOUSE_BUTTON_X2)















static const int MOUSEB_LEFT = MOUSE_BUTTON_LMASK;
static const int MOUSEB_MIDDLE = MOUSE_BUTTON_MMASK;
static const int MOUSEB_RIGHT = MOUSE_BUTTON_RMASK;
static const int MOUSEB_X1 = MOUSE_BUTTON_X1MASK;
static const int MOUSEB_X2 = MOUSE_BUTTON_X2MASK;